-- V6__create_buses_and_drivers.sql
CREATE TABLE buses (
    id VARCHAR(64) PRIMARY KEY,
    bus_number VARCHAR(50) NOT NULL UNIQUE,
    registration_plate VARCHAR(50) NOT NULL UNIQUE,
    capacity INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE', -- AVAILABLE, ASSIGNED, IN_TRANSIT, MAINTENANCE, OUT_OF_SERVICE
    is_electric BOOLEAN NOT NULL DEFAULT FALSE,
    current_odometer_km DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE drivers (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    license_number VARCHAR(80) NOT NULL UNIQUE,
    license_expiry_date DATE NOT NULL,
    phone VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE', -- AVAILABLE, ASSIGNED, ON_DUTY, ON_LEAVE
    preferred_corridor VARCHAR(100),
    rating DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_buses_status ON buses(status);
CREATE INDEX idx_drivers_status ON drivers(status);
